[2025-02-25T07:29:52.128+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-25T07:29:52.172+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emissionAI_ml_pipeline.ingest_data manual__2025-02-25T07:29:46.017487+00:00 [queued]>
[2025-02-25T07:29:52.190+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emissionAI_ml_pipeline.ingest_data manual__2025-02-25T07:29:46.017487+00:00 [queued]>
[2025-02-25T07:29:52.192+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-25T07:29:52.220+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest_data> on 2025-02-25 07:29:46.017487+00:00
[2025-02-25T07:29:52.231+0000] {standard_task_runner.py:72} INFO - Started process 3513 to run task
[2025-02-25T07:29:52.240+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'emissionAI_ml_pipeline', 'ingest_data', 'manual__2025-02-25T07:29:46.017487+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpm7ts0k9k']
[2025-02-25T07:29:52.247+0000] {standard_task_runner.py:105} INFO - Job 45: Subtask ingest_data
[2025-02-25T07:29:52.348+0000] {task_command.py:467} INFO - Running <TaskInstance: emissionAI_ml_pipeline.ingest_data manual__2025-02-25T07:29:46.017487+00:00 [running]> on host c3eb1ce315e0
[2025-02-25T07:29:52.562+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='emissionAI_ml_pipeline' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T07:29:46.017487+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T07:29:46.017487+00:00'
[2025-02-25T07:29:52.567+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-25T07:29:52.892+0000] {logging_mixin.py:190} WARNING - 2025/02/25 07:29:52 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-02-25T07:29:53.088+0000] {logging_mixin.py:190} INFO - üèÉ View run puzzled-squirrel-903 at: http://mlflow:5000/#/experiments/1/runs/20ba6e3f07454a9daaaec37f148c5b9e
[2025-02-25T07:29:53.089+0000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2025-02-25T07:29:53.167+0000] {logging_mixin.py:190} INFO - hello2
[2025-02-25T07:29:53.172+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-25T07:29:53.214+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-25T07:29:53.216+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=emissionAI_ml_pipeline, task_id=ingest_data, run_id=manual__2025-02-25T07:29:46.017487+00:00, execution_date=20250225T072946, start_date=20250225T072952, end_date=20250225T072953
[2025-02-25T07:29:53.263+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-25T07:29:53.304+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-25T07:29:53.307+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
