[2025-02-25T03:52:03.925+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-25T03:52:03.945+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emissionAI_ml_pipeline.ingest_data manual__2025-02-25T03:42:52.358420+00:00 [queued]>
[2025-02-25T03:52:03.957+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emissionAI_ml_pipeline.ingest_data manual__2025-02-25T03:42:52.358420+00:00 [queued]>
[2025-02-25T03:52:03.959+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-25T03:52:03.983+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest_data> on 2025-02-25 03:42:52.358420+00:00
[2025-02-25T03:52:03.991+0000] {standard_task_runner.py:72} INFO - Started process 279 to run task
[2025-02-25T03:52:03.996+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'emissionAI_ml_pipeline', 'ingest_data', 'manual__2025-02-25T03:42:52.358420+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpxc4w90pm']
[2025-02-25T03:52:04.000+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask ingest_data
[2025-02-25T03:52:04.067+0000] {task_command.py:467} INFO - Running <TaskInstance: emissionAI_ml_pipeline.ingest_data manual__2025-02-25T03:42:52.358420+00:00 [running]> on host 953aaae09aef
[2025-02-25T03:52:04.208+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='emissionAI_ml_pipeline' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T03:42:52.358420+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T03:42:52.358420+00:00'
[2025-02-25T03:52:04.212+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-25T03:52:04.387+0000] {logging_mixin.py:190} WARNING - 2025/02/25 03:52:04 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-02-25T03:52:04.461+0000] {logging_mixin.py:190} INFO - üèÉ View run stately-dove-187 at: http://mlflow:5000/#/experiments/1/runs/a1d9a0a2ebc64dcaa3a83c0cd1741f94
[2025-02-25T03:52:04.462+0000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2025-02-25T03:52:04.491+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 39, in ingest_data
    mlflow.log_metric(r, "result")
  File "/home/airflow/.local/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 923, in log_metric
    return MlflowClient().log_metric(
  File "/home/airflow/.local/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1532, in log_metric
    return self._tracking_client.log_metric(
  File "/home/airflow/.local/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 583, in log_metric
    self.store.log_metric(run_id, metric)
  File "/home/airflow/.local/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 398, in log_metric
    LogMetric(
TypeError: bad argument type for built-in operation
[2025-02-25T03:52:04.513+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=emissionAI_ml_pipeline, task_id=ingest_data, run_id=manual__2025-02-25T03:42:52.358420+00:00, execution_date=20250225T034252, start_date=20250225T035203, end_date=20250225T035204
[2025-02-25T03:52:04.558+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-25T03:52:04.560+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 32 for task ingest_data (bad argument type for built-in operation; 279)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 39, in ingest_data
    mlflow.log_metric(r, "result")
  File "/home/airflow/.local/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 923, in log_metric
    return MlflowClient().log_metric(
  File "/home/airflow/.local/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1532, in log_metric
    return self._tracking_client.log_metric(
  File "/home/airflow/.local/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 583, in log_metric
    self.store.log_metric(run_id, metric)
  File "/home/airflow/.local/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 398, in log_metric
    LogMetric(
TypeError: bad argument type for built-in operation
[2025-02-25T03:52:04.612+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-25T03:52:04.680+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-25T03:52:04.690+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
