[2025-02-25T10:46:01.808+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-25T10:46:01.831+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emissionAI_ml_pipeline.ingest_data manual__2025-02-25T10:45:57.759452+00:00 [queued]>
[2025-02-25T10:46:01.846+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emissionAI_ml_pipeline.ingest_data manual__2025-02-25T10:45:57.759452+00:00 [queued]>
[2025-02-25T10:46:01.847+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-25T10:46:01.864+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest_data> on 2025-02-25 10:45:57.759452+00:00
[2025-02-25T10:46:01.879+0000] {standard_task_runner.py:72} INFO - Started process 397 to run task
[2025-02-25T10:46:01.884+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'emissionAI_ml_pipeline', 'ingest_data', 'manual__2025-02-25T10:45:57.759452+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpxq6209gz']
[2025-02-25T10:46:01.889+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask ingest_data
[2025-02-25T10:46:01.959+0000] {task_command.py:467} INFO - Running <TaskInstance: emissionAI_ml_pipeline.ingest_data manual__2025-02-25T10:45:57.759452+00:00 [running]> on host 0a25f6d1fe7d
[2025-02-25T10:46:02.117+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='emissionAI_ml_pipeline' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T10:45:57.759452+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T10:45:57.759452+00:00'
[2025-02-25T10:46:02.120+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-25T10:46:02.142+0000] {data_ingestion.py:36} INFO - One or more environment variables for PostgreSQL database are missing.
[2025-02-25T10:46:02.145+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/src/component/data_ingestion.py", line 37, in get_engine
    raise EnvironmentError("Missing database connection parameters in .env file.")
OSError: Missing database connection parameters in .env file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 36, in ingest_data
    data_ingestion.ingest_data_from_pg_db()
  File "/opt/airflow/src/component/data_ingestion.py", line 54, in ingest_data_from_pg_db
    engine = self.get_engine()
  File "/opt/airflow/src/component/data_ingestion.py", line 46, in get_engine
    raise CustomException(e, sys)
src.utils.exception.CustomException: Error occurred in python script name /opt/airflow/src/component/data_ingestion.py line number 37 error message Missing database connection parameters in .env file.
[2025-02-25T10:46:02.188+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=emissionAI_ml_pipeline, task_id=ingest_data, run_id=manual__2025-02-25T10:45:57.759452+00:00, execution_date=20250225T104557, start_date=20250225T104601, end_date=20250225T104602
[2025-02-25T10:46:02.298+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-25T10:46:02.301+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 67 for task ingest_data (Error occurred in python script name /opt/airflow/src/component/data_ingestion.py line number 37 error message Missing database connection parameters in .env file.; 397)
Traceback (most recent call last):
  File "/opt/airflow/src/component/data_ingestion.py", line 37, in get_engine
    raise EnvironmentError("Missing database connection parameters in .env file.")
OSError: Missing database connection parameters in .env file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 36, in ingest_data
    data_ingestion.ingest_data_from_pg_db()
  File "/opt/airflow/src/component/data_ingestion.py", line 54, in ingest_data_from_pg_db
    engine = self.get_engine()
  File "/opt/airflow/src/component/data_ingestion.py", line 46, in get_engine
    raise CustomException(e, sys)
src.utils.exception.CustomException: Error occurred in python script name /opt/airflow/src/component/data_ingestion.py line number 37 error message Missing database connection parameters in .env file.
[2025-02-25T10:46:02.352+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-25T10:46:02.407+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-25T10:46:02.411+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
