[2025-02-25T07:30:35.461+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-25T07:30:35.486+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emissionAI_ml_pipeline.ingest_data scheduled__2025-02-24T00:00:00+00:00 [queued]>
[2025-02-25T07:30:35.497+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emissionAI_ml_pipeline.ingest_data scheduled__2025-02-24T00:00:00+00:00 [queued]>
[2025-02-25T07:30:35.500+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 5
[2025-02-25T07:30:35.518+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest_data> on 2025-02-24 00:00:00+00:00
[2025-02-25T07:30:35.527+0000] {standard_task_runner.py:72} INFO - Started process 3582 to run task
[2025-02-25T07:30:35.531+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'emissionAI_ml_pipeline', 'ingest_data', 'scheduled__2025-02-24T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmprvxlhwah']
[2025-02-25T07:30:35.538+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask ingest_data
[2025-02-25T07:30:35.606+0000] {task_command.py:467} INFO - Running <TaskInstance: emissionAI_ml_pipeline.ingest_data scheduled__2025-02-24T00:00:00+00:00 [running]> on host c3eb1ce315e0
[2025-02-25T07:30:35.719+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='emissionAI_ml_pipeline' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-24T00:00:00+00:00'
[2025-02-25T07:30:35.722+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-25T07:30:35.894+0000] {logging_mixin.py:190} WARNING - 2025/02/25 07:30:35 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-02-25T07:30:36.009+0000] {logging_mixin.py:190} INFO - üèÉ View run charming-ox-642 at: http://mlflow:5000/#/experiments/1/runs/6da3c27d587149cd9649ee783e44740f
[2025-02-25T07:30:36.012+0000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2025-02-25T07:30:36.038+0000] {logging_mixin.py:190} INFO - hello2
[2025-02-25T07:30:36.039+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-25T07:30:36.056+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-25T07:30:36.058+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=emissionAI_ml_pipeline, task_id=ingest_data, run_id=scheduled__2025-02-24T00:00:00+00:00, execution_date=20250224T000000, start_date=20250225T073035, end_date=20250225T073036
[2025-02-25T07:30:36.113+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-25T07:30:36.155+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-25T07:30:36.160+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
